force-app/main/default/objects/CCountry__c/CCountry__c.object-meta.xml
<CustomObject>
    <description>custom objrcty whiuc imic  the REST Country  field structure</description>
    <label>CCountry</label>
    <nameField>
        <label>CCountry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCountries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCountry__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/CountryCode2__c.field-meta.xml
<CustomField>
    <fullName>CountryCode2__c</fullName>
    <externalId>true</externalId>
    <label>CountryCode2</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/CountryCode3__c.field-meta.xml
<CustomField>
    <fullName>CountryCode3__c</fullName>
    <label>CountryCode3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/RegionalBlock__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlock__c</fullName>
    <label>RegionalBlock</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/SubRegion__c.field-meta.xml
<CustomField>
    <fullName>SubRegion__c</fullName>
    <label>SubRegion</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/jsonCountryWrapper.cls
/*******************************************
wrapper class for Json.  Take care that the
member  name should match exactly  the name
of the  memebers in the JSON  return body
No need to replicate all JSON members, just 
the ones we need
Taker care of  the INNER child elements too.
 * ****************************************/ 
public with sharing class jsonCountryWrapper 
{
    public jsonCountryWrapper() 
    {

    }

public string name;
public string alpha2Code;
public string alpha3Code;
public string capital;
public string region;
public string subregion;

public List<regionalBloc> regionalBlocs;



public class regionalBloc
 {
    public string acronym;
    public string name;
}

public CCountry__c converttoCCountry()
{
  CCountry__c retval = new CCountry__c();
  retval.name = name;
  retval.Capital_City__c = capital;

  retval.CountryCode2__c = alpha2Code;  
  retval.CountryCode3__c = alpha3Code; 
  
  retval.Region__c = region; 
  retval.SubRegion__c = subregion; 

  if(regionalBlocs.size() > 0)
    {
      retval.RegionalBlock__c = regionalBlocs[0].acronym; 
    }

  return retval;
}

    
}