force-app/main/default/objects/CCountry__c/CCountry__c.object-meta.xml
<CustomObject>
    <description>custom objrcty whiuc imic  the REST Country  field structure</description>
    <label>CCountry</label>
    <nameField>
        <label>CCountry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCountries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCountry__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/CountryCode2__c.field-meta.xml
<CustomField>
    <fullName>CountryCode2__c</fullName>
    <externalId>true</externalId>
    <label>CountryCode2</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/CountryCode3__c.field-meta.xml
<CustomField>
    <fullName>CountryCode3__c</fullName>
    <label>CountryCode3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/RegionalBlock__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlock__c</fullName>
    <label>RegionalBlock</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCountry__c/fields/SubRegion__c.field-meta.xml
<CustomField>
    <fullName>SubRegion__c</fullName>
    <label>SubRegion</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CapitalCity__c.field-meta.xml
<CustomField>
    <fullName>CapitalCity__c</fullName>
    <label>CapitalCity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCode2__c.field-meta.xml
<CustomField>
    <fullName>CountryCode2__c</fullName>
    <label>CountryCode2</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCode3__c.field-meta.xml
<CustomField>
    <fullName>CountryCode3__c</fullName>
    <label>CountryCode3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RegionalBloc__c.field-meta.xml
<CustomField>
    <fullName>RegionalBloc__c</fullName>
    <label>RegionalBloc</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubRegion__c.field-meta.xml
<CustomField>
    <fullName>SubRegion__c</fullName>
    <label>SubRegion</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BuildCountryInfo4Lead.cls
public class BuildCountryInfo4Lead 
{



    /******************************************************************************************************
    Method can be invoked from a PB on Lead when leads are created
    ******************************************************************************************************/
    @InvocableMethod(label='Update country Info' description='set country field based on CCountry records')
    public static void SetCountryInfo(List<Lead> leads)
    {
    Set<String> LeadCountries = new Set<String>();
    Set<ID> LeadIDs = new Set<ID>();    
    for(Lead theL :leads)
       {
        LeadCountries.add(theL.Country);
        LeadIDs.add(theL.id);
       }

    //collect the CCountry records for the above Countries
    Map<String,CCountry__c> mapC2C = new Map<String,CCountry__c>();
    For(CCountry__c  theCC :[Select Id,Name,CountryCode2__c,CountryCode3__c,Capital_City__c, Region__c,SubRegion__c,RegionalBlock__c from CCountry__c where Name in :LeadCountries ])
       {
        mapC2C.put(theCC.name,theCC); 
       }   
       
    List<Lead> Leads2Update = new List<Lead>();
    //we need to read  the Leads again because the record is not readable (or creat a new in memory lead)
    for(Lead theLead :leads)     
       {
        Lead theSameLard = new Lead(ID = theLead.id); 
         
        CCountry__c rectCountry = mapC2C.get(theLead.Country);
        if(rectCountry == null)
           continue;

        //pass the values from Lead Countries to the Lead   
        theSameLard.CapitalCity__c = rectCountry.Capital_City__c;
        theSameLard.CountryCode2__c = rectCountry.CountryCode2__c;
        theSameLard.CountryCode3__c = rectCountry.CountryCode3__c;
        theSameLard.Region__c = rectCountry.Region__c;
        theSameLard.SubRegion__c = rectCountry.SubRegion__c;
        theSameLard.RegionalBloc__c = rectCountry.RegionalBlock__c; 

        Leads2Update.add(theSameLard);
       }    
       
    /*************************************************************************
    this approach might create problems. If a big number of Leads are created
    (Marketo integration?) so we might reach some limits. invoking this method  
    from Lead creation context migth be problematic. Put it into a scedulable.
    *************************************************************************/
    List<Database.SaveResult> dbsres = Database.update(Leads2Update,false);       
        
    }
  }